version: "3.9"

services:
  reactvite02:
    # Specify the image to start the container from
    image: node:16.13.2-alpine3.15
    container_name: reactvite02
    tty: true

    # Expose ports (HOST:CONTAINER)
    ports:
      - 3000:3000
      - 5173:5173
      - 5001:5001
      

    # Set environment variables
    #environment:

    # Mount host directories to container directories
    volumes:
      - ./source:/source
      - npm-volume:/source/node_modules

volumes:
  npm-volume:
